import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "SpaceX || Human spaceflight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className + "w-screen overflow-x-hidden"}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
