import React from "react";
import Image from "next/image";

import RelatedTopics from "@/components/RelatedTopics";

const page = () => {
  return (
    <>
      <header>
        <div className="w-full h-screen relative">
          <Image src="/mission/fss.jpg" fill className="object-cover" />
        </div>
        <div className="absolute top-0 left-0 h-full pl-40 w-full flex flex-col items-start justify-center bg-gradient-to-r from-black to-transparent">
          <div className="w-1/3">
            <h1 className="text-7xl font-extrabold">
              The Farside Seismic Suite
            </h1>
            <p className="text-2xl mt-8">
              The Farside Seismic Suite will send two of the sensitive
              seismometers built for the InSight Mars mission to land on the far
              side of the Moon, where they will measure far side moonquakes and
              meteor impacts for the first time ever.
            </p>
          </div>
        </div>
      </header>
      <div className="flex justify-end relative mt-[-3rem]">
        <div className="flex w-[80vw] bg-slate-800 px-10 py-14 gap-20">
          {cards.map((item, index) => (
            <div key={index}>
              <h2 className="uppercase text-teal-400 font-medium mb-2">
                {item.label}
              </h2>
              <p className="text-lg">{item.details}</p>
            </div>
          ))}
        </div>
      </div>
      <main className="px-40 mt-20 max-w-6xl text-2xl">
        {sections.map((item, index) => (
          <section key={index}>
            <h2 className="text-4xl font-medium mt-16 mb-8">{item.heading}</h2>
            <p>{item.text}</p>
          </section>
        ))}
      </main>
      <RelatedTopics
        heading="MORE ABOUT STARS AND GALAXIES"
        topics={relatedCards}
      />
    </>
  );
};

const cards = [
  {
    label: "launch date",
    details: "2025",
  },
  {
    label: "status",
    details: "Future",
  },
];

const sections = [
  {
    heading: "About the mission",
    text: `The Farside Seismic Suite (FSS) will deliver two seismometers (flight-proven through the InSight mission to Mars) to Schrödinger Crater on the far side of the Moon. The vertical Very BroadBand (VBB) seismometer, contributed by the French Space Agency CNES, is the most sensitive flight-ready seismometer ever built, while the Short Period (SP) sensor provided by Kinemetrics Inc. is the most sensitive and mature compact triaxial sensor available for space applications.`,
  },
  {
    heading: "",
    text: "Packaged as a self-sufficient payload, with independent power, communications and thermal control to enable FSS’s survival through the two week long lunar nights and days, the FSS will outlive its lunar lander, provided as part of NASA’s CLPS (Commercial Lunar Payload Services) program, to provide a long-lived seismic experiment capable of answering key scientific questions.",
  },
  {
    heading: "",
    text: `FSS will help define the interior structure of the Moon, a key priority for the planetary science Decadal Survey, where details of the interior from crust to core were identified as critical for understanding how planets’ interiors are formed, as well as in “The Scientific Context for Exploration of the Moon” which included the key science concept: “The structure and composition of the lunar interior provide fundamental information on the evolution of a differentiated planetary body”. Crustal thickness determination far from Apollo stations will re-anchor the crustal thickness estimates from GRAIL gravity measurements, while deep mantle structure will be determined through recordings of known nearside deep moonquakes at greater distances than Apollo. Schrödinger crater is an impact basin resurfaced by impact melt, and local structure determination is uniquely suited to investigate impact processes. Finally, recording the seismic background vibration below the noise floor of Apollo gives access to seismic hum generated by micrometeorite impacts.`,
  },
];

const relatedCards = [
  {
    img: "/2008.webp",
    title: "Herschel space observatory",
  },
  {
    img: "/2010.jpg",
    title: "infrared astronomical satellite",
  },
  {
    img: "/2012.webp",
    title: "NuStar",
  },
  {
    img: "/2015.jpg",
    title: "Cold atom Laboratory",
  },
  {
    img: "/2016.jpeg",
    title: "Galxy evolution Explorer",
  },
];

export default page;
